{{- if .Values.env.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strapi-chart.fullname" . }}
  labels:
    {{- include "strapi-chart.labels" . | nindent 4 }}
data:
  {{- with .Values.env.configmap }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}