pipeline {

    agent { node { label 'deploy' } }
    parameters {
        string(name: 'SERVICE', defaultValue: 'vault', description: '', trim: true)
        string(name: 'NAMESPACE', defaultValue: 'infra', description: '', trim: true)
        string(name: 'VAULT_KEY_1', defaultValue: 'XMWJE7IrUygbYJ3+/oHvHBVpMCtSCf1n/nEe+LK8WJAM', description: '', trim: true)
        string(name: 'VAULT_KEY_2', defaultValue: 'smDse6fsx5bS6fZ4kCEHgXnzCaopZ3qUTa9xLslR38Fg', description: '', trim: true)
        string(name: 'VAULT_KEY_3', defaultValue: 'JqofceakghubZf5P75SWZ0hl9Xd4ZuYrmZfYYNsSJFm/', description: '', trim: true)
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '30', numToKeepStr: '5'))
        disableResume()
    }
    environment {
        SERVICE = "$params.SERVICE"
        NAMESPACE = "$params.NAMESPACE"
        VAULT_KEY_1 = "$params.VAULT_KEY_1"
        VAULT_KEY_2 = "$params.VAULT_KEY_2"
        VAULT_KEY_3 = "$params.VAULT_KEY_3"
    }

    stages {
        stage('Unseal Vault') {
            steps {
                echo "Start patching ...."
                script {
                    withKubeConfig([namespace: "$NAMESPACE"]) {
                      sh '''
                        kubectl exec -i ${SERVICE}-0 -n $NAMESPACE -- vault operator unseal $VAULT_KEY_1
                        kubectl exec -i ${SERVICE}-0 -n $NAMESPACE -- vault operator unseal $VAULT_KEY_2
                        kubectl exec -i ${SERVICE}-0 -n $NAMESPACE -- vault operator unseal $VAULT_KEY_3
                      '''
                    }
                }
                echo "Finish patching ...."
            }
        }
    }
}
