replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.25"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""
  
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 50%
  
podAnnotations: {}

terminationGracePeriodSeconds: 30

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 80

initContainers: []

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: dev-example-tls
  #    hosts:
  #      - dev.example.com

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

startupProbe: {}
#  httpGet:
#    path: /
#    port: http
  
livenessProbe: {}
#  httpGet:
#    path: /
#    port: http
readinessProbe: {}
#  httpGet:
#    path: /
#    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - resource:
        name: memory
        target:
          averageValue: 1000Mi
          type: AverageValue
      type: Resource
    - resource:
        name: cpu
        target:
          averageValue: 500m
          type: AverageValue
      type: Resource
  behavior:
    scaleDown:
      policiesPeriodSeconds: 300
      policiesType: Pods
      policiesValue: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 90
    scaleUp:
      policiesPeriodSeconds: 90
      policiesType: Pods
      policiesValue: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 60

nodeSelector: {}

tolerations: []

affinity: {}

env:
  configmap: {}
  secret: {}

