apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "redisinsight-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5540
      protocol: TCP
      name: http
  selector:
    {{- include "redisinsight-chart.selectorLabels" . | nindent 4 }}
