- hosts: kubeadm-master
#  become: yes
  tasks:
    - name: Wait till vault is created
      kubernetes.core.k8s_info:
        kind: Pod
        wait: yes
        name: vault-0
        namespace: infra
        wait_sleep: 10
        wait_timeout: 60
      register: vault_pod_info
      ignore_errors: True

    - name: Init token vault
      kubernetes.core.k8s_exec:
        namespace: infra
        pod: vault-0
        command: vault operator init
      ignore_errors: True
      register: command_status
      when: vault_pod_info.failed == true

    - name: Check last command status
      debug:
        msg: "{{ command_status.stdout_lines }}"
      when:
        - vault_pod_info.failed == true
        - command_status.rc != 0

