apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  ACTIVEMQ_ADMIN_LOGIN: 'admin|base64'
  ACTIVEMQ_ADMIN_PASSWORD: 'admin|base64'
