apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
data:
  ACTIVEMQ_ADMIN_LOGIN: YWRtaW4=
  ACTIVEMQ_ADMIN_PASSWORD: YWRtaW4=
