apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
data:
  ACTIVEMQ_ADMIN_USERNAME: {{ .Values.admin.username | default "admin" | b64enc }}
  ACTIVEMQ_ADMIN_PASSWORD: {{ .Values.admin.password | default "admin" | b64enc }}
