apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
data:
  ACTIVEMQ_ADMIN_LOGIN: 'admin|base64'
  ACTIVEMQ_ADMIN_PASSWORD: 'admin|base64'
