apiVersion: v1
kind: ServiceAccount
metadata:
  name: renew-linkerd-crt-sa
  namespace: infra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: renew-linkerd-crt-sa-binding
subjects:
  - kind: ServiceAccount
    name: renew-linkerd-crt-sa
    namespace: infra
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renew-linkerd-crt-cronjob
  namespace: infra
spec:
  schedule: "1 1 1 1 *" # Modify schedule to run the renewal certificate
  startingDeadlineSeconds: 120
  concurrencyPolicy: Allow
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: renew-linkerd-crt-sa
          containers:
            - name: renew-linkerd-crt-job
              image: xxx/linkerd-renew-crt:latest # Build docker image for this
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash", "-c"]
              args:
                - step certificate create root.linkerd.cluster.local ca.crt ca.key --profile root-ca --no-password --insecure && step certificate create identity.linkerd.cluster.local issuer.crt issuer.key --profile intermediate-ca --not-after 876000h --no-password --insecure --ca ca.crt --ca-key ca.key && linkerd upgrade --crds | kubectl apply -f - && linkerd upgrade --set proxyInit.runAsRoot=true --identity-trust-anchors-file ca.crt --identity-issuer-certificate-file issuer.crt --identity-issuer-key-file issuer.key --force | kubectl apply -f -
          restartPolicy: Never
          terminationGracePeriodSeconds: 120
