apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    chart: "jenkins"
    repoURL: "https://charts.jenkins.io"  # note: the oci:// syntax is not included.
    targetRevision: 5.1.23
    helm:
      parameters:
        - name: "persistence.size"
          value: "2Gi"
        - name: "controller.image.tag"
          value: "latest-jdk17"
  destination:
    server: https://kubernetes.default.svc
    namespace: default