apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    chart: kafka
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 29.0.3
    helm:
      parameters:
        - name: "sasl.interbroker.password"
          value: "123456"
          forceString: true
        - name: "sasl.controller.password"
          value: "123456"
          forceString: true
        - name: "sasl.client.passwords"
          value: "123456"
          forceString: true
        - name: "kraft.clusterId"
          value: "123456"
          forceString: true
        - name: "controller.replicaCount"
          value: "1"
        - name: "controller.persistence.size"
          value: "1Gi"
        - name: "broker.replicaCount"
          value: "1"
        - name: "broker.persistence.size"
          value: "1Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true