apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  source:
    chart: mariadb
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 18.2.0
    helm:
      parameters:
        - name: "fullnameOverride"
          value: "mariadb"
        - name: "image.tag"
          value: '11.3.2'
        - name: "auth.rootPassword"
          value: "123456"
          forceString: true
        - name: "auth.username"
          value: "superuser"
        - name: "auth.password"
          value: "123456"
          forceString: true
        - name: "auth.database"
          value: "test"
        - name: "primary.persistence.size"
          value: 1Gi
        - name: "primary.service.type"
          value: "LoadBalancer"
      valuesObject:
        initdbScripts:
          init.sql: |
            CREATE USER app identified by '123456';
            CREATE DATABASE `phuocle-blog`;
            GRANT ALL PRIVILEGES ON `phuocle-blog`.* TO 'app'@'%';
            CREATE DATABASE `phuocle-blog`;
            GRANT ALL PRIVILEGES ON `phucninh-blog`.* TO 'app'@'%';
            CREATE DATABASE `strapi`;
            GRANT ALL PRIVILEGES ON `strapi`.* TO 'app'@'%';
            FLUSH PRIVILEGES;
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
