apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    chart: minio
    repoURL: https://charts.min.io
    targetRevision: 5.2.0
    helm:
      parameters:
        - name: "image.repository"
          value: "minio/minio"
        - name: "image.tag"
          value: "latest"
        - name: "mcImage.repository"
          value: "minio/minio"
        - name: "mcImage.tag"
          value: "latest"
        - name: "replicas"
          value: "1"
        - name: "mode"
          value: "standalone"
        - name: "bucketRoot"
          value: "data"
        - name: "rootUser"
          value: "admin@phucninh.pro"
          forceString: true
        - name: "rootPassword"
          value: "LHPkttlhp123"
          forceString: true
        - name: "persistence.storageClass"
          value: "longhorn"
        - name: "mountPath"
          value: "/data"
        - name: "persistence.size"
          value: "1Gi"
        - name: "resources.requests.memory"
          value: "500Mi"
      valuesObject:
        securityContext:
          enabled: true
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0
          fsGroupChangePolicy: "OnRootMismatch"
          readOnlyRootFilesystem: false
        users:
          - accessKey: 4Srhkmgzbu44a7WvC6Wa
            secretKey: GX7wRO0MfoUacVT5BrUd4mVzvyhTgcR3JeJkX8eP
            policy: consoleAdmin
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true