apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    chart: mongodb
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 15.6.0
    helm:
      parameters:
        - name: "fullnameOverride"
          value: "mongodb"
        - name: "image.tag"
          value: '7.0.9'
        - name: "auth.enabled"
          value: "true"
        - name: "auth.rootPassword"
          value: "123456"
          forceString: true
        - name: "auth.usernames[0]"
          value: "app"
        - name: "auth.passwords[0]"
          value: "123456"
          forceString: true
        - name: "auth.databases[0]"
          value: "test"
        - name: "persistence.size"
          value: "1Gi"
        - name: "service.type"
          value: "LoadBalancer"
        - name: "extraEnvVars[0].name"
          value: "EXPERIMENTAL_DOCKER_DESKTOP_FORCE_QEMU"
        - name: "extraEnvVars[0].value"
          value: "1"
          forceString: true

  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
