apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phucninh-blog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 22.4.11
    helm:
      parameters:
        - name: fullnameOverride
          value: 'phucninh-blog'
        - name: image.tag
          value: '6.5.4'
        - name: wordpressUsername
          value: 'admin'
        - name: wordpressPassword
          value: '123456'
          forceString: true
        - name: wordpressEmail
          value: 'admin@phucninh.me'
        - name: wordpressFirstName
          value: 'Phuc'
        - name: wordpressLastName
          value: 'Ninh'
        - name: wordpressBlogName
          value: "Phuc Ninh's Blog"
        - name: service.type
          value: 'ClusterIP'
        - name: persistence.size
          value: '1Gi'
        - name: mariadb.enabled
          value: 'false'
        - name: externalDatabase.host
          value: 'mariadb.infra'
        - name: externalDatabase.port
          value: '3306'
        - name: externalDatabase.user
          value: 'app'
        - name: externalDatabase.password
          value: '123456'
          forceString: true
        - name: externalDatabase.database
          value: 'phucninh-blog'
    chart: wordpress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true