apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phuocle-blog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 23.0.1
    helm:
      parameters:
        - name: fullnameOverride
          value: 'phuocle-blog'
        - name: global.storageClass
          value: 'longhorn-nfs'
        - name: image.tag
          value: '6.5.5'
        - name: wordpressUsername
          value: 'admin'
        - name: wordpressEmail
          value: 'admin@phuocle.me'
        - name: wordpressFirstName
          value: 'Phuoc'
        - name: wordpressLastName
          value: 'Le'
        - name: wordpressBlogName
          value: "Phuoc Le's Blog"
        - name: wordpressPassword
          value: '123456'
          forceString: true
        - name: service.type
          value: 'ClusterIP'
        - name: persistence.existingClaim
          value: 'phuocle-blog'
        - name: mariadb.enabled
          value: 'false'
        - name: externalDatabase.host
          value: 'mariadb'
        - name: externalDatabase.port
          value: '3306'
        - name: externalDatabase.user
          value: 'app'
        - name: externalDatabase.password
          value: '123456'
          forceString: true
        - name: externalDatabase.database
          value: 'phuocle-blog'
    chart: wordpress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default