apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 15.4.0
    helm:
      parameters:
        - name: "fullnameOverride"
          value: "postgres"
        - name: "image.tag"
          value: '16.3.0'
        - name: "global.auth.postgresPassword"
          value: "123456"
          forceString: true
        - name: "global.auth.username"
          value: "superuser"
        - name: "global.auth.password"
          value: "123456"
          forceString: true
        - name: "global.auth.database"
          value: "test"
        - name: "auth.postgresPassword"
          value: "123456"
          forceString: true
        - name: "auth.username"
          value: "superuser"
        - name: "auth.password"
          value: "123456"
          forceString: true
        - name: "auth.database"
          value: "test"
        - name: "primary.persistence.size"
          value: 1Gi
        - name: "readReplicas.persistence.size"
          value: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true