apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-insight
  namespace: argocd
spec:
  project: default
  source:
    chart: redis-insight
    repoURL: registry-1.docker.io/phuoc
    targetRevision: 2.0.0
    helm:
      parameters:
        - name: "environment.RITRUSTEDORIGINS"
          value: "https://redis-insight.phucninh.pro"
        - name: "persistence.enabled"
          value: "true"
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
