apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 19.5.5
    helm:
      parameters:
        - name: "fullnameOverride"
          value: "redis"
        - name: "image.tag"
          value: '7.2.5'
        - name: "architecture"
          value: "standalone"
        - name: "master.persistence.size"
          value: 1Gi
        - name: "auth.enabled"
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
