apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strapi
  namespace: argocd
spec:
  project: default
  source:
    chart: strapi
    repoURL: registry-1.docker.io/phuoc
    targetRevision: 1.0.0
    helm:
      parameters:
        - name: "image.repository"
          value: "phuoc/strapi"
        - name: "image.pullPolicy"
          value: "IfNotPresent"
        - name: "image.tag"
          value: "latest"
        - name: "persistence.size"
          value: "1Gi"
        - name: "env.configmap.DATABASE_CLIENT"
          value: "mysql2"
        - name: "env.configmap.DATABASE_HOST"
          value: "mariadb.infra"
        - name: "env.configmap.DATABASE_NAME"
          value: "strapi"
        - name: "env.configmap.DATABASE_PORT"
          value: "3306"
          forceString: true
        - name: "env.secrets.DATABASE_USERNAME"
          value: "app"
          forceString: true
        - name: "env.secrets.DATABASE_PASSWORD"
          value: "123456"
          forceString: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true