apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: vault
    helm:
      releaseName: vault
      parameters:
        - name: "server.dataStorage.size"
          value: "1Gi"
        - name: "server.dev.enabled"
          value: "false"
        - name: "server.dev.devRootToken"
          value: "root"
        - name: "ui.enabled"
          value: "false"
        - name: "csi.enabled"
          value: "false"
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.0
