apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kustomize
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: demo-kustomize
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 512Mi
          env:
          - name: MEM_TOTAL_MB
            valueFrom:
              resourceFieldRef:
                resource: limits.memory