apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kustomize
  namespace: default  
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: demo-kustomize
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              path: /
              port: 80