apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phucninh-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dev.phucninh.pro
      secretName: dev-phucninh-pro-tls
    - hosts:
        - blog.phucninh.pro
      secretName: blog-phucninh-pro-tls
    - hosts:
        - api.phucninh.pro
      secretName: api-phucninh-pro-tls
  rules:
    - host: dev.phucninh.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
    - host: api.phucninh.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi
                port:
                  number: 1337
    - host: blog.phucninh.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phucninh-blog
                port:
                  number: 80
