apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phuocle-blog
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-nfs
  volumeMode: Filesystem