# Default values for redisinsight-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: redislabs/redisinsight
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2.50.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 0

service:
  type: ClusterIP
  port: 5540

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

initContainers: []
#  - name: init
#    image: busybox
#    command:
#      - /bin/sh
#      - '-c'
#      - |
#        chown -R 1001 /db
#    resources: {}
#    volumeMounts:
#      - name: db
#        mountPath: /db
#    terminationMessagePath: /dev/termination-log
#    terminationMessagePolicy: File

affinity: {}

persistence:
  enabled: true
  existingClaim: ""
  mountPath: /data
  subPath: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 100Mi

environment:
  RITRUSTEDORIGINS: 'https://redis-insight.phucninh.pro'
