- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      add_host:
        name: "master_node"
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: remove swap
      shell: "swapoff -a"

    - name: sed fstab
      shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: join cluster
      shell: "{{ hostvars['master_node'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
