{{- if .Values.env.secret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "demo-chart.labels" . | nindent 4 }}
  {{- with .Values.env.secret }}
data:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}