- hosts: localhost
  vars:
    USERNAME: 'ubuntu'
  tasks:
    - name: "create .kube directory for {{ USERNAME }}"
      become: yes
      file:
        path: "/home/{{ USERNAME }}/.kube"
        state: directory
        mode: 0755
        owner: "{{ USERNAME }}"
        group: "{{ USERNAME }}"

    - name: get the username running
      become: false
      local_action: command whoami
      register: local_username

    - name: "copy ~/ansible/config to {{ USERNAME }}'s kube config"
      become: yes
      copy:
        src: "/home/{{ local_username.stdout }}/ansible/config"
        dest: "/home/{{ USERNAME }}/.kube/config"
        remote_src: yes
        owner: "{{ USERNAME }}"
        group: "{{ USERNAME }}"
        mode: "0400"