- hosts: localhost
  become: yes
  vars:
    USERNAME: 'ubuntu'
  tasks:
    - name: "create .kube directory for {{ USERNAME }}"
      file:
        path: "/home/{{ USERNAME }}/.kube"
        state: directory
        mode: 0755
        owner: "{{ USERNAME }}"
        group: "{{ USERNAME }}"

    - name: "copy ./ansible/config to {{ USERNAME }}'s kube config"
      copy:
        src: "~/ansible/config"
        dest: "/home/{{ USERNAME }}/.kube/config"
        remote_src: yes
        owner: "{{ USERNAME }}"
        group: "{{ USERNAME }}"
        mode: "0400"