- hosts: localhost
  vars:
    USERNAME: 'ubuntu'
    master_ip: ""
  tasks:
    - name: Get IP from kubconfig
      become_user:
      command: cat ~/.kube/config |awk -v RS='([0-9]+\\.){3}[0-9]+' 'RT{print RT}'| awk 'NR==1{print $1}'
    - debug:
        var: master_ip


